### ISSUE TITLE
As an innovator, I want to be able to join a design process session using just the group keyword and my name so that I can start the design process in a timely manner

### ISSUE THREAD

**Issue by machang19** [CMU-17-356/Peerdea#1]
Card: As an innovator, I want to be able to join a design process session using just the group keyword and my name so that I can start the design process in a timely manner
Conversation: We want to remove any hassle when using the site, so we will only use group keyword and name to validate individuals
Confirmation: This is done when five test users given a group keyword are able to figure out how to join a session within the first minute of visiting the site.

**Comment by judyzhang25** [comment]
Joining a group is possible if the group name is known.
