### ISSUE TITLE
As an innovator in  a group of trusted peers, I want to create a review session protected by a group keyword, so that no one I don’t trust sees and steals my ideas. 

### ISSUE THREAD

**Issue by machang19** [CMU-17-356/Peerdea#6]
Card: As an innovator in  a group of trusted peers, I want to create a review session protected by a group keyword, so that no one I don’t trust sees and steals my ideas. 
Conversation: Anyone can create a group keyword. When a user wants to join a review session they simply give their name and the group keyword for the group they want to join and begin. 
Confirmation: A user can only start the design process if they have a valid group keyword and only users that have used the same group keyword will see their ideas.

**Comment by judyzhang25** [comment]
People can create or join groups as long as they know the name of the group. They can also create their own screen names.
